{
 "title": "Ceph - Cluster",
 "description": "Ceph Cluster overview.\r\n",
 "tags": [
  "ceph",
  "cluster"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "Interval",
    "query": "5s,10s,30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "job",
    "label": "Cluster",
    "query": {
     "query": "label_values(ceph_mon_quorum_status, job)"
    }
   }
  ]
 },
 "panels": [
  { "title": "CLUSTER STATE", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Status",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "ceph_health_status{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Monitors In Quorum",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(ceph_mon_quorum_status{job=\"$job\"})"
    }
   ]
  },
  {
   "title": "Pools",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(ceph_pool_objects{job=\"$job\"})"
    }
   ]
  },
  {
   "title": "Cluster Capacity",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "ceph_cluster_total_bytes{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Used Capacity",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "ceph_cluster_total_used_bytes{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Used Capacity",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "ceph_cluster_total_used_bytes{job=\"$job\"}/ceph_cluster_total_bytes{job=\"$job\"}*100"
    }
   ]
  },
  { "title": "OSD STATE", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "OSDs IN",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(ceph_osd_in{job=\"$job\"})"
    }
   ]
  },
  {
   "title": "OSDs OUT",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(ceph_osd_up{job=\"$job\"}) - count(ceph_osd_in{job=\"$job\"})"
    }
   ]
  },
  {
   "title": "OSDs UP",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(ceph_osd_up{job=\"$job\"})"
    }
   ]
  },
  {
   "title": "OSDs DOWN",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(ceph_osd_up{job=\"$job\"} == 0) OR vector(0)"
    }
   ]
  },
  {
   "title": "Agerage PGs per OSD",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(ceph_osd_numpg{job=\"$job\"})"
    }
   ]
  },
  {
   "title": "Average OSD Apply Latency",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 6 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(ceph_osd_apply_latency_ms{job=\"$job\"})"
    }
   ]
  },
  {
   "title": "Average OSD Commit Latency",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 6 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(ceph_osd_commit_latency_ms{job=\"$job\"})"
    }
   ]
  },
  {
   "title": "Average Monitor Latency",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 6 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(ceph_paxos_refresh_latency_sum{job=\"$job\"}[1m]))/clamp_min(sum(increase(ceph_paxos_refresh_latency_count{job=\"$job\"}[1m])),1)"
    }
   ]
  },
  { "title": "CLUSTER", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Capacity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "ceph_cluster_total_bytes{job=\"$job\"}-ceph_cluster_total_used_bytes{job=\"$job\"}",
     "legendFormat": "Available"
    },
    {
     "expr": "ceph_cluster_total_used_bytes{job=\"$job\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "ceph_cluster_total_bytes{job=\"$job\"}",
     "legendFormat": "Total Capacity"
    }
   ]
  },
  {
   "title": "IOPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(rate(ceph_osd_op_r{job=\"$job\"}[$interval]))",
     "legendFormat": "read"
    },
    {
     "expr": "sum(rate(ceph_osd_op_w{job=\"$job\"}[$interval]))",
     "legendFormat": "write"
    },
    {
     "expr": "sum(rate(ceph_osd_op_rw{job=\"$job\"}[$interval]))",
     "legendFormat": "overwrite"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(irate(ceph_osd_op_r_out_bytes{job=\"$job\"}[$interval]))",
     "legendFormat": "read"
    },
    {
     "expr": "sum(irate(ceph_osd_op_w_in_bytes{job=\"$job\"}[$interval]))",
     "legendFormat": "write"
    },
    {
     "expr": "sum(irate(ceph_osd_op_rw_in_bytes{job=\"$job\"}[$interval]))",
     "legendFormat": "overwrite"
    }
   ]
  },
  { "title": "LATENCY", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "OSD Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 14, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "1000*sum(increase(ceph_osd_op_r_latency_sum{job=\"$job\"}[1m]))/clamp_min(sum(increase(ceph_osd_op_r_latency_count{job=\"$job\"}[1m])),1)",
     "legendFormat": "read"
    },
    {
     "expr": "1000*sum(increase(ceph_osd_op_w_latency_sum{job=\"$job\"}[1m]))/clamp_min(sum(increase(ceph_osd_op_w_latency_count{job=\"$job\"}[1m])),1)",
     "legendFormat": "write"
    },
    {
     "expr": "1000*sum(increase(ceph_osd_op_rw_latency_sum{job=\"$job\"}[1m]))/clamp_min(sum(increase(ceph_osd_op_rw_latency_count{job=\"$job\"}[1m])),1)",
     "legendFormat": "overwrite"
    }
   ]
  },
  {
   "title": "MDS Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 19 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "ceph_mds_reply_latency_sum{job=\"$job\"}/ceph_mds_reply_latency_count{job=\"$job\"}",
     "legendFormat": "latency"
    }
   ]
  },
  {
   "title": "RGW Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "1000 * sum(increase(ceph_rgw_put_initial_lat_sum{job=\"$job\"}[1m])) / clamp_min(sum(increase(ceph_rgw_put_initial_lat_count{job=\"$job\"}[1m])), 1)",
     "legendFormat": "PUT"
    },
    {
     "expr": "1000 * sum(increase(ceph_rgw_get_initial_lat_sum{job=\"$job\"}[1m])) / clamp_min(sum(increase(ceph_rgw_get_initial_lat_count{job=\"$job\"}[1m])), 1)",
     "legendFormat": "GET"
    }
   ]
  },
  {
   "title": "RBD Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "1000 * sum(increase(ceph_rbd_write_latency_sum{job=\"$job\"}[1m])) / clamp_min(sum(increase(ceph_rbd_write_latency_count{job=\"$job\"}[1m])), 1)",
     "legendFormat": "WRITE"
    },
    {
     "expr": "1000 * sum(increase(ceph_rbd_read_latency_sum{job=\"$job\"}[1m])) / clamp_min(sum(increase(ceph_rbd_read_latency_count{job=\"$job\"}[1m])), 1)",
     "legendFormat": "READ"
    }
   ]
  },
  { "title": "OBJECTS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Objects in the Cluster",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(ceph_pool_objects{job=\"$job\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Objects Unfound / Degraded / Misplaced",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ceph_num_objects_unfound{job=\"$job\"}",
     "legendFormat": "Unfound"
    },
    {
     "expr": "ceph_num_objects_degraded{job=\"$job\"}",
     "legendFormat": "Degraded"
    },
    {
     "expr": "ceph_num_objects_misplaced{job=\"$job\"}",
     "legendFormat": "Misplaced"
    }
   ]
  },
  {
   "title": "PGs",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(ceph_pg_active{job=\"$job\"})",
     "legendFormat": "Active"
    },
    {
     "expr": "sum(ceph_pg_clean{job=\"$job\"})",
     "legendFormat": "Clean"
    },
    {
     "expr": "sum(ceph_pg_peering{job=\"$job\"})",
     "legendFormat": "Peering"
    },
    {
     "expr": "sum(ceph_pg_degraded{job=\"$job\"})",
     "legendFormat": "Degraded"
    },
    {
     "expr": "sum(ceph_pg_stale{job=\"$job\"})",
     "legendFormat": "Stale"
    },
    {
     "expr": "sum(ceph_unclean_pgs{job=\"$job\"})",
     "legendFormat": "Unclean"
    },
    {
     "expr": "sum(ceph_pg_undersized{job=\"$job\"})",
     "legendFormat": "Undersized"
    },
    {
     "expr": "sum(ceph_pg_incomplete{job=\"$job\"})",
     "legendFormat": "Incomplete"
    },
    {
     "expr": "sum(ceph_pg_forced_backfill{job=\"$job\"})",
     "legendFormat": "Forced Backfill"
    },
    {
     "expr": "sum(ceph_pg_inconsistent{job=\"$job\"})",
     "legendFormat": "Inconsistent"
    },
    {
     "expr": "sum(ceph_pg_forced_recovery{job=\"$job\"})",
     "legendFormat": "Forced Recovery"
    },
    {
     "expr": "sum(ceph_pg_creating{job=\"$job\"})",
     "legendFormat": "Creating"
    },
    {
     "expr": "sum(ceph_pg_wait_backfill{job=\"$job\"})",
     "legendFormat": "Wait Backfill"
    },
    {
     "expr": "sum(ceph_pg_deep{job=\"$job\"})",
     "legendFormat": "Deep"
    },
    {
     "expr": "sum(ceph_pg_scrubbing{job=\"$job\"})",
     "legendFormat": "Scrubbing"
    },
    {
     "expr": "sum(ceph_pg_recovering{job=\"$job\"})",
     "legendFormat": "Recovering"
    },
    {
     "expr": "sum(ceph_pg_repair{job=\"$job\"})",
     "legendFormat": "Repair"
    },
    {
     "expr": "sum(ceph_pg_down{job=\"$job\"})",
     "legendFormat": "Down"
    },
    {
     "expr": "sum(ceph_pg_peered{job=\"$job\"})",
     "legendFormat": "Peered"
    },
    {
     "expr": "sum(ceph_pg_backfill{job=\"$job\"})",
     "legendFormat": "Backfill"
    },
    {
     "expr": "sum(ceph_pg_remapped{job=\"$job\"})",
     "legendFormat": "Remapped"
    },
    {
     "expr": "sum(ceph_pg_backfill_toofull{job=\"$job\"})",
     "legendFormat": "Backfill Toofull"
    }
   ]
  },
  {
   "title": "Faulty PGs",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(ceph_pg_degraded{job=\"$job\"})",
     "legendFormat": "Degraded"
    },
    {
     "expr": "sum(ceph_pg_stale{job=\"$job\"})",
     "legendFormat": "Stale"
    },
    {
     "expr": "sum(ceph_pg_undersized{job=\"$job\"})",
     "legendFormat": "Undersized"
    }
   ]
  },
  {
   "title": "Recovery Operations",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(ceph_osd_recovery_ops{job=\"$job\"}[$interval]))",
     "legendFormat": "OPS"
    }
   ]
  },
  { "title": "OSD Utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "OSD Storage Used",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "ceph_osd_stat_bytes_used{job=\"$job\"}",
     "legendFormat": "{{ceph_daemon}}"
    }
   ]
  },
  {
   "title": "OSD Used %",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 51 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "ceph_osd_stat_bytes_used{job=\"$job\"}/ceph_osd_stat_bytes{job=\"$job\"}*100",
     "legendFormat": "{{ceph_daemon}}"
    }
   ]
  }
 ]
}