{
 "title": "Camunda Metrics Dashboard",
 "description": "Camunda Metrics Dashboard",
 "tags": [ "camunda" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(camunda_root_process_instances_active, namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Загальні метрики Process Engine",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "User Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(camunda_user_count{namespace=\"$namespace\"}) without(instance, pod)",
     "legendFormat": "Camunda User Count"
    }
   ]
  },
  {
   "title": "Authorizations count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(camunda_authorization_count{namespace=\"$namespace\"}) without(instance, pod)",
     "legendFormat": "Camunda Authorization Count"
    }
   ]
  },
  {
   "title": "Active Deployments",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(camunda_deployments{namespace=\"$namespace\"}) without(instance, pod)",
     "legendFormat": "Camunda Deployments"
    }
   ]
  },
  {
   "title": "Active Process Definitions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(camunda_active_process_definitions{namespace=\"$namespace\"}) without(instance, pod)",
     "legendFormat": "Camunda Active Process Definitions"
    }
   ]
  },
  {
   "title": "Загальні метрики бізнес-процесів",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 }
  },
  {
   "title": "Root Process Instances",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(camunda_root_process_instances{namespace=\"$namespace\"}) without(instance, pod)",
     "legendFormat": "Camunda Total Root Process Instances"
    },
    {
     "expr": "avg(camunda_root_process_instances_active{namespace=\"$namespace\"}) without(instance, pod)",
     "legendFormat": "Camunda Active Root Process Instances"
    },
    {
     "expr": "avg(camunda_root_process_instances_suspended{namespace=\"$namespace\"}) without(instance, pod)",
     "legendFormat": "Camunda Suspended Root Process Instances"
    },
    {
     "expr": "avg(camunda_root_process_instances_completed{namespace=\"$namespace\"}) without(instance, pod)",
     "legendFormat": "Camunda Completed Root Process Instances"
    },
    {
     "expr": "avg(camunda_root_process_instances_terminated{namespace=\"$namespace\"}) without(instance, pod)",
     "legendFormat": "Camunda Terminated Root Process Instances"
    }
   ]
  },
  {
   "title": "User Tasks",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(camunda_active_user_tasks{namespace=\"$namespace\"}) without(instance, pod)",
     "legendFormat": "Camunda Total User Tasks"
    },
    {
     "expr": "avg(camunda_active_user_tasks_assigned{namespace=\"$namespace\"}) without(instance, pod)",
     "legendFormat": "Camunda Assigned User Tasks"
    },
    {
     "expr": "avg(camunda_active_user_tasks_unassigned{namespace=\"$namespace\"}) without(instance, pod)",
     "legendFormat": "Camunda Unassigned User Tasks"
    }
   ]
  },
  {
   "title": "Active Incidents",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(camunda_active_incidents{namespace=\"$namespace\"}) without(instance, pod)",
     "legendFormat": "Camunda Active Incidents"
    }
   ]
  },
  {
   "title": "Загальні метрики обміну повідомленнями в рамках бізнес-процесу",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 }
  },
  {
   "title": "Active Signal Event Subscriptions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(camunda_active_signal_event_subscriptions{namespace=\"$namespace\"}) without(instance, pod)",
     "legendFormat": "Camunda Active Signal Event Subscriptions"
    }
   ]
  },
  {
   "title": "Active Compensate Event Subscriptions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(camunda_active_compensate_event_subscriptions{namespace=\"$namespace\"}) without(instance, pod)",
     "legendFormat": "Camunda Active Compensate Event Subscriptions"
    }
   ]
  },
  {
   "title": "Active Conditional Event Subscriptions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(camunda_active_conditional_event_subscriptions{namespace=\"$namespace\"}) without(instance, pod)",
     "legendFormat": "Camunda Active Conditional Event Subscriptions"
    }
   ]
  },
  {
   "title": "Active Message Event Subscriptions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(camunda_active_message_event_subscriptions{namespace=\"$namespace\"}) without(instance, pod)",
     "legendFormat": "Camunda Active Message Event Subscriptions"
    }
   ]
  },
  {
   "title": "Загальні метрики асинхронного виконання задач бізнес-процесу",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 }
  },
  {
   "title": "Message Jobs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(camunda_message_jobs{namespace=\"$namespace\"}) without(instance, pod)",
     "legendFormat": "Camunda Message Jobs"
    }
   ]
  },
  {
   "title": "Timer Jobs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 53 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(camunda_timer_jobs{namespace=\"$namespace\"}) without(instance, pod)",
     "legendFormat": "Camunda Timer Jobs"
    }
   ]
  },
  {
   "title": "Executable Timer Jobs",
   "type": "graph",
   "description": "Timers that are ready to be executed (past due date)",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 53 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(camunda_executable_timer_jobs{namespace=\"$namespace\"}) without(instance, pod)",
     "legendFormat": "Camunda Executable Timer Jobs"
    }
   ]
  },
  {
   "title": "Executable Jobs",
   "type": "graph",
   "description": "Jobs ready to be executed (past due date)",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 53 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(camunda_executable_jobs{namespace=\"$namespace\"}) without(instance, pod)",
     "legendFormat": "Camunda Executable Jobs"
    }
   ]
  },
  {
   "title": "Видалення історичних даних виконання бізнес-процесів",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 }
  },
  {
   "title": "Removed process instances",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(camunda_history_cleanup_removed_process_instances{namespace=\"$namespace\"}) without(instance, pod)",
     "legendFormat": "Camunda Removed History Process Instances"
    }
   ]
  },
  {
   "title": "Removed tasks",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 62 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(camunda_history_cleanup_removed_task_metrics{namespace=\"$namespace\"}) without(instance, pod)",
     "legendFormat": "Camunda Removed History Tasks"
    }
   ]
  }
 ]
}