{
 "title": "Redis Monitoring",
 "description": "Redis Dashboard for Prometheus Redis Exporter 1.x",
 "tags": [
  "prometheus",
  "redis"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(redis_up, namespace)"
    }
   },
   { "name": "pod", "label": "Pod", "query": { "query": "label_values(redis_up, pod)" } }
  ]
 },
 "panels": [
  {
   "title": "Max Uptime",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(max_over_time(redis_uptime_in_seconds{pod=~\"$pod\", namespace=~\"$namespace\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Clients",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 2, "x": 3, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(redis_connected_clients{pod=~\"$pod\", namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 3, "x": 5, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(100 * (redis_memory_used_bytes{pod=~\"$pod\", namespace=~\"$namespace\"}  / redis_memory_max_bytes{pod=~\"$pod\", namespace=~\"$namespace\"}))"
    }
   ]
  },
  {
   "title": "Total Commands / sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(redis_commands_processed_total{pod=~\"$pod\", namespace=~\"$namespace\"} [1m])) by (cmd)",
     "legendFormat": "{{ cmd }}"
    }
   ]
  },
  {
   "title": "Hits / Misses per Sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(redis_keyspace_hits_total{pod=~\"$pod\", namespace=~\"$namespace\"}[5m])",
     "legendFormat": "hits, {{ pod }}"
    },
    {
     "expr": "irate(redis_keyspace_misses_total{pod=~\"$pod\", namespace=~\"$namespace\"}[5m])",
     "legendFormat": "misses, {{ pod }}"
    }
   ]
  },
  {
   "title": "Total Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "redis_memory_used_bytes{pod=~\"$pod\", namespace=~\"$namespace\"}",
     "legendFormat": "used, {{ pod }}"
    },
    {
     "expr": "redis_memory_max_bytes{pod=~\"$pod\", namespace=~\"$namespace\"}",
     "legendFormat": "max, {{ pod }}"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(redis_net_input_bytes_total{pod=~\"$pod\", namespace=~\"$namespace\"}[5m]))",
     "legendFormat": "{{ input }}"
    },
    {
     "expr": "sum(rate(redis_net_output_bytes_total{pod=~\"$pod\", namespace=~\"$namespace\"}[5m]))",
     "legendFormat": "{{ output }}"
    }
   ]
  },
  {
   "title": "Total Items per DB",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum (redis_db_keys{pod=~\"$pod\", namespace=~\"$namespace\"}) by (db, pod)",
     "legendFormat": "{{ db }}, {{ pod }}"
    }
   ]
  },
  {
   "title": "Expiring vs Not-Expiring Keys",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (redis_db_keys{pod=~\"$pod\", namespace=~\"$namespace\"}) by (pod) - sum (redis_db_keys_expiring{pod=~\"$pod\", namespace=~\"$namespace\"}) by (pod)",
     "legendFormat": "not expiring, {{ pod }}"
    },
    {
     "expr": "sum (redis_db_keys_expiring{pod=~\"$pod\", namespace=~\"$namespace\"}) by (pod)",
     "legendFormat": "expiring, {{ pod }}"
    }
   ]
  },
  {
   "title": "Expired/Evicted Keys",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(redis_expired_keys_total{pod=~\"$pod\", namespace=~\"$namespace\"}[5m])) by (pod)",
     "legendFormat": "expired, {{ pod }}"
    },
    {
     "expr": "sum(rate(redis_evicted_keys_total{pod=~\"$pod\", namespace=~\"$namespace\"}[5m])) by (pod)",
     "legendFormat": "evicted, {{ pod }}"
    }
   ]
  },
  {
   "title": "Connected/Blocked Clients",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(redis_connected_clients{pod=~\"$pod\", namespace=~\"$namespace\"})",
     "legendFormat": "connected"
    },
    {
     "expr": "sum(redis_blocked_clients{pod=~\"$pod\", namespace=~\"$namespace\"})",
     "legendFormat": "blocked"
    }
   ]
  }
 ]
}