{
 "title": "Experimental Dashboard",
 "tags": [
  "experimental",
  "ecoppho",
  "registry",
  "alerting"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "namespace", "query": "registry-name" }
  ]
 },
 "panels": [
  { "title": "OKD", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Not Ready Pods",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pod) (kube_pod_status_ready{namespace=\"$namespace\",pod!~\".*reloader.*|.*operator.*|.*job.*|.*jenkins-agent.*|.*build.*|.*audit-clean.*|.*-full.*\",condition=\"false\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Pods Restarts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pod) (increase(kube_pod_container_status_restarts_total{namespace=\"registry-name\",pod!~\".*reloader.*|.*operator.*|.*job.*|.*jenkins-agent.*|.*build.*|.*audit-clean.*|.*-full.*\"}[1h]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "OOM Killer",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pod) (kube_pod_container_status_last_terminated_reason{namespace=\"registry-name\",pod!~\".*reloader.*|.*operator.*|.*job.*|.*jenkins-agent.*|.*build.*|.*audit-clean.*|.*-full.*\",reason=\"OOMKilled\"}) OR on() vector(0)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Keycloak IAM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "User Login [officer-realm]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (realm) (increase(keycloak_logins_total{realm=~\"ecoppho-officer.*\"}[1h]))",
       "legendFormat": "success"
      },
      {
       "expr": "sum by (realm) (increase(keycloak_failed_login_attempts_total{realm=~\"ecoppho-officer.*\"}[1h]))",
       "legendFormat": "failure"
      },
      {
       "expr": "sum by (realm) (increase(keycloak_login_attempts_total{realm=~\"ecoppho-officer.*\"}[1h]))",
       "legendFormat": "total"
      }
     ]
    },
    {
     "title": "Token Refresh [officer-realm]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (realm) (increase(keycloak_refresh_tokens_total{realm=~\"ecoppho-officer.*\"}[1h]))",
       "legendFormat": "success"
      },
      {
       "expr": "sum by (realm) (increase(keycloak_refresh_tokens_errors_total{realm=~\"ecoppho-officer.*\"}[1h]))",
       "legendFormat": "failure"
      }
     ]
    },
    {
     "title": "User Login [admin-realm]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (client_id) (increase(keycloak_logins_total{realm=~\"ecoppho-admin.*\"}[1h]))",
       "legendFormat": "{{client_id}}"
      }
     ]
    },
    {
     "title": "User Logout [officer-realm]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "targets": [
      {
       "expr": "sum  (increase(keycloak_user_event_LOGOUT_total{realm=~\"ecoppho-officer.*\"}[1h]))",
       "legendFormat": "logout"
      }
     ]
    }
   ]
  },
  {
   "title": "PostgreSQL Operational Cluster",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (cluster) (ccp_nodemx_mem_usage_in_bytes{namespace=\"registry-name\",cluster=\"operational\"})",
       "legendFormat": "{{cluster}}"
      }
     ]
    },
    {
     "title": "Disk Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100 * ((sum by (cluster) (ccp_nodemx_data_disk_total_bytes{namespace=\"registry-name\",cluster=\"operational\"}) - sum by (cluster) (ccp_nodemx_data_disk_available_bytes{namespace=\"registry-name\",cluster=\"operational\"})) / sum by (cluster) (ccp_nodemx_data_disk_total_bytes{namespace=\"registry-name\",cluster=\"operational\"}))",
       "legendFormat": "{{cluster}}"
      }
     ]
    },
    {
     "title": "Database Size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "targets": [
      {
       "expr": "sum by (dbname) (ccp_database_size_bytes{namespace=\"registry-name\",cluster=\"operational\",dbname!~\"postgres|registry_dev_.*|registry_template\"}) / (1024 * 1024)",
       "legendFormat": "{{dbname}}"
      }
     ]
    },
    {
     "title": "Connection Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100 * (sum(pg_settings_superuser_reserved_connections{namespace=\"registry-name\",cluster=\"operational\"}) + sum(pg_stat_activity_count{namespace=\"registry-name\",cluster=\"operational\"}) ) / sum(pg_settings_max_connections{namespace=\"registry-name\",cluster=\"operational\"})",
       "legendFormat": "operational"
      }
     ]
    },
    {
     "title": "Connection by State",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (state) (pg_stat_activity_count{namespace=\"registry-name\",cluster=\"operational\",state=\"active\"})",
       "legendFormat": "{{state}}"
      },
      {
       "expr": "sum by (state) (pg_stat_activity_count{namespace=\"registry-name\",cluster=\"operational\",state=\"idle in transaction\"})",
       "legendFormat": "{{state}}"
      },
      {
       "expr": "sum by (state) (pg_stat_activity_count{namespace=\"registry-name\",cluster=\"operational\",state=\"idle\"})",
       "legendFormat": "{{state}}"
      },
      {
       "expr": "sum(pg_settings_max_connections{namespace=\"registry-name\",cluster=\"operational\"})",
       "legendFormat": "total"
      }
     ]
    },
    {
     "title": "Max Active Tx Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max by (datname) (pg_stat_activity_max_tx_duration{namespace=\"registry-name\",cluster=\"operational\",datname!~\"postgres|registry_dev_.*|registry_template|template.*\",state=\"active\"})",
       "legendFormat": "{{datname}}"
      }
     ]
    },
    {
     "title": "Cache Hit Ratio",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100 * sum by (dbname) (ccp_stat_database_blks_hit{namespace=\"registry-name\",cluster=\"operational\",dbname!~\"audit|postgres|registry_dev_.*|registry_template|template.*\"}) / ( sum by (dbname) (ccp_stat_database_blks_hit{namespace=\"registry-name\",cluster=\"operational\",dbname!~\"audit|postgres|registry_dev_.*|registry_template|template.*\"}) + sum by (dbname) (ccp_stat_database_blks_read{namespace=\"registry-name\",cluster=\"operational\",dbname!~\"audit|postgres|registry_dev_.*|registry_template|template.*\"}))",
       "legendFormat": "{{dbname}}"
      }
     ]
    },
    {
     "title": "WAL Size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "targets": [
      {
       "expr": "sum by (cluster) (ccp_wal_activity_total_size_bytes{namespace=\"registry-name\",cluster=\"operational\"}) / (1024 * 1024)",
       "legendFormat": "{{cluster}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Application Services Hikari Connection Pool",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 }
  },
  {
   "title": "Connections By State",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (hikaricp_connections_active{namespace=\"registry-name\"})",
     "legendFormat": "active"
    },
    {
     "expr": "sum (hikaricp_connections_idle{namespace=\"registry-name\"})",
     "legendFormat": "idle"
    },
    {
     "expr": "sum (hikaricp_connections_pending{namespace=\"registry-name\"})",
     "legendFormat": "pending"
    },
    {
     "expr": "sum (hikaricp_connections_max{namespace=\"registry-name\"})",
     "legendFormat": "max connections"
    }
   ]
  },
  {
   "title": "Pending Connection Ratio by Service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * sum by (service) (hikaricp_connections_pending{namespace=\"registry-name\"}) / (sum by (service) (hikaricp_connections_active{namespace=\"registry-name\"}) + sum by (service) (hikaricp_connections_idle{namespace=\"registry-name\"}) + sum by (service) (hikaricp_connections_pending{namespace=\"registry-name\"}))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Active Connection Ratio by Service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * sum by (service) (hikaricp_connections_active{namespace=\"registry-name\"}) / (sum by (service) (hikaricp_connections_active{namespace=\"registry-name\"}) + sum by (service) (hikaricp_connections_idle{namespace=\"registry-name\"}))",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Connection Timeout By Service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (service) (increase(hikaricp_connections_timeout_total{namespace=\"registry-name\"}[5m]))",
     "legendFormat": "{{service}}"
    }
   ]
  },
  { "title": "Kafka Consumer Group Lag", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Consumer Group Lag [topic: data-factory-inbound]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_lag{namespace=\"registry-name\", topic=~\"create-.*-inbound|update-.*-inbound|delete-.*-inbound\"}) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Consumer Group Lag Delta [topic: data-factory-inbound]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (topic) (delta(kafka_consumergroup_lag{namespace=\"registry-name\",topic=~\"create-.*-inbound|update-.*-inbound|delete-.*-inbound\"}[5m]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Consumer Group Lag [topic: bpm-history]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_lag{namespace=\"registry-name\", topic=~\"bpm-history-.*\"}) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Consumer Group Lag Delta [topic: bpm-history]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (topic) (delta(kafka_consumergroup_lag{namespace=\"registry-name\",topic=~\"bpm-history-.*\"}[5m]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Consumer Group Lag [topic:excerpts]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_lag{namespace=\"registry-name\", topic=~\"generate-excerpt.*\"}) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Consumer Group Lag [topic: audit-events]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_lag{namespace=\"registry-name\", topic=\"audit-events\"}) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Redis",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "redis_memory_used_bytes{namespace=\"registry-name\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "DB Keys Volume",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "max(redis_db_keys{namespace=~\"registry-name\"})"
      }
     ]
    }
   ]
  },
  { "title": "Ceph", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 } },
  {
   "title": "Scrubbing by Pool",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(ceph_pg_scrubbing) by (pool_id)",
     "legendFormat": "pool id - {{pool_id}}"
    }
   ]
  },
  {
   "title": "Deep Scrubbing by Pool",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "sum(ceph_pg_deep) by (pool_id)", "legendFormat": "pool id - {{pool_id}}" }
   ]
  },
  {
   "title": "PGs Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "sum(ceph_pg_active)", "legendFormat": "Active" },
    { "expr": "sum(ceph_pg_clean)", "legendFormat": "Clean" },
    { "expr": "sum(ceph_pg_peering)", "legendFormat": "Peering" },
    { "expr": "sum(ceph_pg_degraded)", "legendFormat": "Degraded" },
    { "expr": "sum(ceph_pg_stale)", "legendFormat": "Stale" },
    { "expr": "sum(ceph_unclean_pgs)", "legendFormat": "Unclean" },
    { "expr": "sum(ceph_pg_undersized)", "legendFormat": "Undersized" },
    { "expr": "sum(ceph_pg_incomplete)", "legendFormat": "Incomplete" },
    { "expr": "sum(ceph_pg_forced_backfill)", "legendFormat": "Forced Backfill" },
    { "expr": "sum(ceph_pg_inconsistent)", "legendFormat": "Inconsistent" },
    { "expr": "sum(ceph_pg_forced_recovery)", "legendFormat": "Forced Recovery" },
    { "expr": "sum(ceph_pg_creating)", "legendFormat": "Creating" },
    { "expr": "sum(ceph_pg_wait_backfill)", "legendFormat": "Wait Backfill" },
    { "expr": "sum(ceph_pg_deep)", "legendFormat": "Deep" },
    { "expr": "sum(ceph_pg_scrubbing)", "legendFormat": "Scrubbing" },
    { "expr": "sum(ceph_pg_recovering)", "legendFormat": "Recovering" },
    { "expr": "sum(ceph_pg_repair)", "legendFormat": "Repair" },
    { "expr": "sum(ceph_pg_down)", "legendFormat": "Down" },
    { "expr": "sum(ceph_pg_peered)", "legendFormat": "Peered" },
    { "expr": "sum(ceph_pg_backfill)", "legendFormat": "Backfill" },
    { "expr": "sum(ceph_pg_remapped)", "legendFormat": "Remapped" },
    { "expr": "sum(ceph_pg_backfill_toofull)", "legendFormat": "Backfill Toofull" }
   ]
  },
  {
   "title": "OSD Read & Write Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "1000*sum(increase(ceph_osd_op_r_latency_sum[1m]))/clamp_min(sum(increase(ceph_osd_op_r_latency_count[1m])),1)",
     "legendFormat": "read"
    },
    {
     "expr": "1000*sum(increase(ceph_osd_op_w_latency_sum[1m]))/clamp_min(sum(increase(ceph_osd_op_w_latency_count[1m])),1)",
     "legendFormat": "write"
    },
    {
     "expr": "1000*sum(increase(ceph_osd_op_rw_latency_sum[1m]))/clamp_min(sum(increase(ceph_osd_op_rw_latency_count[1m])),1)",
     "legendFormat": "overwrite"
    }
   ]
  }
 ]
}