{
 "title": "Load Volumes, load nodes CPU,RAM",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "Load memory per node",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "round((100*((node_memory_MemTotal_bytes)-(node_memory_MemAvailable_bytes)))/node_memory_MemTotal_bytes)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Load CPU per node",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "round(100*instance:node_cpu_utilisation:rate1m)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Volumes",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "round((100*kubelet_volume_stats_used_bytes)/kubelet_volume_stats_capacity_bytes)",
     "legendFormat": "{{namespace}}: {{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "Nodes \"Not ready\"",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition=\"Ready\",status!=\"true\"})"
    }
   ]
  },
  {
   "title": "CEPH health status on ${cluster} cluster",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "absent(ceph_health_status == 1)"
    }
   ]
  },
  {
   "title": "Ceph ROOT volumes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "round((100*ceph_cluster_total_used_bytes)/ceph_cluster_total_bytes)"
    }
   ]
  }
 ]
}