{
 "title": "Redash Monitoring",
 "description": "Redash monitoring dashboard",
 "tags": [
  "redash",
  "analytics"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "namespace", "label": "Namespace", "query": { "query": "query_result(redash_info)" } },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "query_result(redash_info{namespace=\"$namespace\"})"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Dashboards",
   "type": "stat",
   "description": "Number of the dashboards available in Redash",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redash_dashboards_count{namespace=\"$namespace\", instance=\"$instance\"}",
     "legendFormat": "Number of the dashboards"
    }
   ]
  },
  {
   "title": "Queries",
   "type": "stat",
   "description": "Amount of queries present in Redash ",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "redash_queries_count{namespace=\"$namespace\", instance=\"$instance\"}",
     "legendFormat": "Amount of queries"
    }
   ]
  },
  {
   "title": "Widgets",
   "type": "stat",
   "description": "Amount of widgets used by the Dashboards to represent queried data",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "redash_wigets_count{namespace=\"$namespace\", instance=\"$instance\"}",
     "legendFormat": "Amount of queries"
    }
   ]
  },
  {
   "title": "Celery Queues",
   "type": "graph",
   "description": "Amount of messages in the Celery queues",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "redash_queues_celery{namespace=\"$namespace\", instance=\"$instance\"}",
     "legendFormat": "Amount of tasks"
    }
   ]
  },
  {
   "title": "Queries Queues",
   "type": "graph",
   "description": "Amount of queries in queues",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "redash_queues_queries{namespace=\"$namespace\", instance=\"$instance\"}",
     "legendFormat": "Amount of queries"
    }
   ]
  },
  {
   "title": "Scheduled Queries Queues",
   "type": "graph",
   "description": "Number of the scheduled queries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "redash_queues_scheduled_queries{namespace=\"$namespace\", instance=\"$instance\"}",
     "legendFormat": "Amount of queries"
    }
   ]
  },
  {
   "title": "Query Results",
   "type": "stat",
   "description": "Amount of query results stored in repository database",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "redash_query_results_count{namespace=\"$namespace\", instance=\"$instance\"}",
     "legendFormat": "Cached queries"
    }
   ]
  },
  {
   "title": "Query Results Size, Mb",
   "type": "stat",
   "description": "Size of query results stored in the repository database",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "redash_query_results_size_bytes{namespace=\"$namespace\", instance=\"$instance\"}/1024/1024",
     "legendFormat": "Cache size, Mb"
    }
   ]
  },
  {
   "title": "Outdated Queries",
   "type": "stat",
   "description": "Amount of outdated queries",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "redash_outdated_queries_count{namespace=\"$namespace\", instance=\"$instance\"}  ",
     "legendFormat": "Amount of outdated queries"
    }
   ]
  },
  {
   "title": "Unused Query Results",
   "type": "stat",
   "description": "Amount of query results that were never used or displayed",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "redash_unused_query_results_count{namespace=\"$namespace\", instance=\"$instance\"}",
     "legendFormat": "Never used cached queries"
    }
   ]
  },
  {
   "title": "Redash Repository Size, Mb",
   "type": "graph",
   "description": "Size of the database used by Redash for internal purposes",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "redash_db_size_bytes{namespace=\"$namespace\", instance=\"$instance\"}/1024/1024",
     "legendFormat": "Repository size, Mb"
    }
   ]
  },
  {
   "title": "Memory Used by Redis, Mb",
   "type": "graph",
   "description": "Amount of memory used by Redis ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "redash_redis_used_memory_bytes{namespace=\"$namespace\", instance=\"$instance\"}/1024/1024",
     "legendFormat": "Redis memory used, Mb"
    }
   ]
  }
 ]
}