{
 "title": "Node Exporter: Memory",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "job", "label": "Job", "query": "node-exporter" },
   {
    "name": "node",
    "label": "Host",
    "query": {
     "query": "label_values(node_uname_info{job=\"$job\"}, instance)"
    }
   },
   {
    "name": "diskdevices",
    "query": "[a-z]+|nvme[0-9]+n[0-9]+|mmcblk[0-9]+"
   }
  ]
 },
 "panels": [
  { "title": "Memory Meminfo", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Memory Active / Inactive",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_Inactive_bytes{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "Inactive - Memory which has been less recently used.  It is more eligible to be reclaimed for other purposes"
    },
    {
     "expr": "node_memory_Active_bytes{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "Active - Memory that has been used more recently and usually not reclaimed unless absolutely necessary"
    }
   ]
  },
  {
   "title": "Memory Committed",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_Committed_AS_bytes{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "Committed_AS - Amount of memory presently allocated on the system"
    },
    {
     "expr": "node_memory_CommitLimit_bytes{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "CommitLimit - Amount of  memory currently available to be allocated on the system"
    }
   ]
  },
  {
   "title": "Memory Active / Inactive Detail",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_Inactive_file_bytes{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "Inactive_file - File-backed memory on inactive LRU list"
    },
    {
     "expr": "node_memory_Inactive_anon_bytes{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "Inactive_anon - Anonymous and swap cache on inactive LRU list, including tmpfs (shmem)"
    },
    {
     "expr": "node_memory_Active_file_bytes{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "Active_file - File-backed memory on active LRU list"
    },
    {
     "expr": "node_memory_Active_anon_bytes{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "Active_anon - Anonymous and swap cache on active least-recently-used (LRU) list, including tmpfs"
    }
   ]
  },
  {
   "title": "Memory Writeback and Dirty",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_Writeback_bytes{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "Writeback - Memory which is actively being written back to disk"
    },
    {
     "expr": "node_memory_WritebackTmp_bytes{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "WritebackTmp - Memory used by FUSE for temporary writeback buffers"
    },
    {
     "expr": "node_memory_Dirty_bytes{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "Dirty - Memory which is waiting to get written back to the disk"
    }
   ]
  },
  {
   "title": "Memory Shared and Mapped",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_Mapped_bytes{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "Mapped - Used memory in mapped pages files which have been mapped, such as libraries"
    },
    {
     "expr": "node_memory_Shmem_bytes{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "Shmem - Used shared memory (shared between several processes, thus including RAM disks)"
    },
    {
     "expr": "node_memory_ShmemHugePages_bytes{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "ShmemHugePages - Memory used by shared memory (shmem) and tmpfs allocated  with huge pages"
    },
    {
     "expr": "node_memory_ShmemPmdMapped_bytes{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "ShmemPmdMapped - Amount of shared (shmem/tmpfs) memory backed by huge pages"
    }
   ]
  },
  {
   "title": "Memory Slab",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_SUnreclaim_bytes{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "SUnreclaim - Part of Slab, that cannot be reclaimed on memory pressure"
    },
    {
     "expr": "node_memory_SReclaimable_bytes{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "SReclaimable - Part of Slab, that might be reclaimed, such as caches"
    }
   ]
  },
  {
   "title": "Memory Vmalloc",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_VmallocChunk_bytes{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "VmallocChunk - Largest contiguous block of vmalloc area which is free"
    },
    {
     "expr": "node_memory_VmallocTotal_bytes{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "VmallocTotal - Total size of vmalloc memory area"
    },
    {
     "expr": "node_memory_VmallocUsed_bytes{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "VmallocUsed - Amount of vmalloc area which is used"
    }
   ]
  },
  {
   "title": "Memory Bounce",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_Bounce_bytes{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "Bounce - Memory used for block device bounce buffers"
    }
   ]
  },
  {
   "title": "Memory Anonymous",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_AnonHugePages_bytes{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "AnonHugePages - Memory in anonymous huge pages"
    },
    {
     "expr": "node_memory_AnonPages_bytes{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "AnonPages - Memory in user pages not backed by files"
    }
   ]
  },
  {
   "title": "Memory Kernel / CPU",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_KernelStack_bytes{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "KernelStack - Kernel memory stack. This is not reclaimable"
    },
    {
     "expr": "node_memory_Percpu_bytes{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "PerCPU - Per CPU memory allocated dynamically by loadable modules"
    }
   ]
  },
  {
   "title": "Memory HugePages Counter",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_memory_HugePages_Free{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "HugePages_Free - Huge pages in the pool that are not yet allocated"
    },
    {
     "expr": "node_memory_HugePages_Rsvd{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "HugePages_Rsvd - Huge pages for which a commitment to allocate from the pool has been made, but no allocation has yet been made"
    },
    {
     "expr": "node_memory_HugePages_Surp{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "HugePages_Surp - Huge pages in the pool above the value in /proc/sys/vm/nr_hugepages"
    }
   ]
  },
  {
   "title": "Memory HugePages Size",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_HugePages_Total{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "HugePages - Total size of the pool of huge pages"
    },
    {
     "expr": "node_memory_Hugepagesize_bytes{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "Hugepagesize - Huge Page size"
    }
   ]
  },
  {
   "title": "Memory DirectMap",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_DirectMap1G_bytes{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "DirectMap1G - Amount of pages mapped as this size"
    },
    {
     "expr": "node_memory_DirectMap2M_bytes{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "DirectMap2M - Amount of pages mapped as this size"
    },
    {
     "expr": "node_memory_DirectMap4k_bytes{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "DirectMap4K - Amount of pages mapped as this size"
    }
   ]
  },
  {
   "title": "Memory Unevictable and MLocked",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_Unevictable_bytes{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "Unevictable - Amount of unevictable memory that can't be swapped out for a variety of reasons"
    },
    {
     "expr": "node_memory_Mlocked_bytes{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "MLocked - Size of pages locked to memory using the mlock() system call"
    }
   ]
  },
  {
   "title": "Memory NFS",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_NFS_Unstable_bytes{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "NFS Unstable - Memory in NFS pages sent to the server, but not yet committed to the storage"
    }
   ]
  },
  { "title": "Memory Vmstat", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 81 } },
  {
   "title": "Memory Pages In / Out",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(node_vmstat_pgpgin{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "Pagesin - Page in operations"
    },
    {
     "expr": "irate(node_vmstat_pgpgout{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "Pagesout - Page out operations"
    }
   ]
  },
  {
   "title": "Memory Pages Swap In / Out",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(node_vmstat_pswpin{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "Pswpin - Pages swapped in"
    },
    {
     "expr": "irate(node_vmstat_pswpout{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "Pswpout - Pages swapped out"
    }
   ]
  },
  {
   "title": "Memory Page Faults",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(node_vmstat_pgfault{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "Pgfault - Page major and minor fault operations"
    },
    {
     "expr": "irate(node_vmstat_pgmajfault{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "Pgmajfault - Major page fault operations"
    },
    {
     "expr": "irate(node_vmstat_pgfault{instance=\"$node\",job=\"$job\"}[$__rate_interval])  - irate(node_vmstat_pgmajfault{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "Pgminfault - Minor page fault operations"
    }
   ]
  },
  {
   "title": "OOM Killer",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(node_vmstat_oom_kill{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "oom killer invocations "
    }
   ]
  }
 ]
}