{
 "title": "Node Exporter: System",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "job", "label": "Job", "query": "node-exporter" },
   {
    "name": "node",
    "label": "Host",
    "query": {
     "query": "label_values(node_uname_info{job=\"$job\"}, instance)"
    }
   },
   {
    "name": "diskdevices",
    "query": "[a-z]+|nvme[0-9]+n[0-9]+|mmcblk[0-9]+"
   }
  ]
 },
 "panels": [
  { "title": "System Timesync", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Time Synchronized Drift",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "node_timex_estimated_error_seconds{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "Estimated error in seconds"
    },
    {
     "expr": "node_timex_offset_seconds{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "Time offset in between local system and reference clock"
    },
    {
     "expr": "node_timex_maxerror_seconds{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "Maximum error in seconds"
    }
   ]
  },
  {
   "title": "Time PLL Adjust",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_timex_loop_time_constant{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "Phase-locked loop time adjust"
    }
   ]
  },
  {
   "title": "Time Synchronized Status",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_timex_sync_status{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "Is clock synchronized to a reliable server (1 = yes, 0 = no)"
    },
    {
     "expr": "node_timex_frequency_adjustment_ratio{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "Local clock frequency adjustment"
    }
   ]
  },
  {
   "title": "Time Misc",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "node_timex_tick_seconds{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "Seconds between clock ticks"
    },
    {
     "expr": "node_timex_tai_offset_seconds{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "International Atomic Time (TAI) offset"
    }
   ]
  },
  { "title": "System Processes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Processes Status",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_procs_blocked{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "Processes blocked waiting for I/O to complete"
    },
    {
     "expr": "node_procs_running{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "Processes in runnable state"
    }
   ]
  },
  {
   "title": "Processes State",
   "type": "timeseries",
   "description": "Enable with --collector.processes argument on node-exporter",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_processes_state{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "{{ state }}"
    }
   ]
  },
  {
   "title": "Processes  Forks",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(node_forks_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "Processes forks second"
    }
   ]
  },
  {
   "title": "Processes Memory",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "irate(process_virtual_memory_bytes{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "Processes virtual memory size in bytes"
    },
    {
     "expr": "process_resident_memory_max_bytes{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "Maximum amount of virtual memory available in bytes"
    },
    {
     "expr": "irate(process_virtual_memory_bytes{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "Processes virtual memory size in bytes"
    },
    {
     "expr": "irate(process_virtual_memory_max_bytes{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "Maximum amount of virtual memory available in bytes"
    }
   ]
  },
  {
   "title": "PIDs Number and Limit",
   "type": "timeseries",
   "description": "Enable with --collector.processes argument on node-exporter",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_processes_pids{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "Number of PIDs"
    },
    {
     "expr": "node_processes_max_processes{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "PIDs limit"
    }
   ]
  },
  {
   "title": "Process schedule stats Running / Waiting",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "irate(node_schedstat_running_seconds_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "CPU {{ cpu }} - seconds spent running a process"
    },
    {
     "expr": "irate(node_schedstat_waiting_seconds_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "CPU {{ cpu }} - seconds spent by processing waiting for this CPU"
    }
   ]
  },
  {
   "title": "Threads Number and Limit",
   "type": "timeseries",
   "description": "Enable with --collector.processes argument on node-exporter",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_processes_threads{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "Allocated threads"
    },
    {
     "expr": "node_processes_max_threads{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "Threads limit"
    }
   ]
  },
  { "title": "System Misc", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 } },
  {
   "title": "Context Switches / Interrupts",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(node_context_switches_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "Context switches"
    },
    {
     "expr": "irate(node_intr_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "Interrupts"
    }
   ]
  },
  {
   "title": "System Load",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_load1{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "Load 1m"
    },
    {
     "expr": "node_load5{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "Load 5m"
    },
    {
     "expr": "node_load15{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "Load 15m"
    }
   ]
  },
  {
   "title": "CPU Frequency Scaling",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "targets": [
    {
     "expr": "node_cpu_scaling_frequency_hertz{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "CPU {{ cpu }}"
    },
    {
     "expr": "avg(node_cpu_scaling_frequency_max_hertz{instance=\"$node\",job=\"$job\"})",
     "legendFormat": "Max"
    },
    {
     "expr": "avg(node_cpu_scaling_frequency_min_hertz{instance=\"$node\",job=\"$job\"})",
     "legendFormat": "Min"
    }
   ]
  },
  {
   "title": "Pressure Stall Information",
   "type": "timeseries",
   "description": "https://docs.kernel.org/accounting/psi.html",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(node_pressure_cpu_waiting_seconds_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "CPU some"
    },
    {
     "expr": "rate(node_pressure_memory_waiting_seconds_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "Memory some"
    },
    {
     "expr": "rate(node_pressure_memory_stalled_seconds_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "Memory full"
    },
    {
     "expr": "rate(node_pressure_io_waiting_seconds_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "I/O some"
    },
    {
     "expr": "rate(node_pressure_io_stalled_seconds_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "I/O full"
    }
   ]
  },
  {
   "title": "Interrupts Detail",
   "type": "timeseries",
   "description": "Enable with --collector.interrupts argument on node-exporter",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(node_interrupts_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "{{ type }} - {{ info }}"
    }
   ]
  },
  {
   "title": "Schedule timeslices executed by each cpu",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(node_schedstat_timeslices_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "CPU {{ cpu }}"
    }
   ]
  },
  {
   "title": "Entropy",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_entropy_available_bits{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "Entropy available to random number generators"
    }
   ]
  },
  {
   "title": "CPU time spent in user and system contexts",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "irate(process_cpu_seconds_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "Time spent"
    }
   ]
  },
  {
   "title": "File Descriptors",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "process_max_fds{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "Maximum open file descriptors"
    },
    {
     "expr": "process_open_fds{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "Open file descriptors"
    }
   ]
  },
  { "title": "Systemd", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 113 } },
  {
   "title": "Systemd Sockets",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 114 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(node_systemd_socket_accepted_connections_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "{{ name }} Connections"
    }
   ]
  },
  {
   "title": "Systemd Units State",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 114 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_systemd_units{instance=\"$node\",job=\"$job\",state=\"activating\"}",
     "legendFormat": "Activating"
    },
    {
     "expr": "node_systemd_units{instance=\"$node\",job=\"$job\",state=\"active\"}",
     "legendFormat": "Active"
    },
    {
     "expr": "node_systemd_units{instance=\"$node\",job=\"$job\",state=\"deactivating\"}",
     "legendFormat": "Deactivating"
    },
    {
     "expr": "node_systemd_units{instance=\"$node\",job=\"$job\",state=\"failed\"}",
     "legendFormat": "Failed"
    },
    {
     "expr": "node_systemd_units{instance=\"$node\",job=\"$job\",state=\"inactive\"}",
     "legendFormat": "Inactive"
    }
   ]
  }
 ]
}