{
 "title": "Spring Boot",
 "description": "Dashboard for Spring Application Statistics(by micrometer-prometheus).\r\nThis is a fork of dashboard 6756, fixed for Spring Boot 2.3 and support for Jetty instead of Tomcat.",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(jvm_memory_used_bytes, namespace)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(jvm_memory_used_bytes{namespace=~\"$namespace\"}, pod)"
    }
   },
   {
    "name": "memory_pool_heap",
    "label": "Memory Pool (heap)",
    "query": {
     "query": "label_values(jvm_memory_used_bytes{pod=\"$pod\", area=\"heap\"},id)"
    }
   },
   {
    "name": "memory_pool_nonheap",
    "label": "Memory Pool (nonheap)",
    "query": {
     "query": "label_values(jvm_memory_used_bytes{pod=\"$pod\", area=\"nonheap\"},id)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Basic Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "process_uptime_seconds{pod=\"$pod\", pod=\"$pod\"}"
    }
   ]
  },
  {
   "title": "Heap Used",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 5, "x": 6, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{pod=\"$pod\", pod=\"$pod\", area=\"heap\"})*100/sum(jvm_memory_max_bytes{pod=\"$pod\", area=\"heap\", pod=\"$pod\"})"
    }
   ]
  },
  {
   "title": "Non-Heap Used",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 5, "x": 11, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{pod=\"$pod\", area=\"nonheap\", pod=\"$pod\"})*100/sum(jvm_memory_max_bytes{pod=\"$pod\", area=\"nonheap\", pod=\"$pod\"})"
    }
   ]
  },
  {
   "title": "Process Open Files",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "process_files_open_files{pod=\"$pod\", pod=\"$pod\"}",
     "legendFormat": "Open Files"
    },
    {
     "expr": "process_files_max_files{pod=\"$pod\", pod=\"$pod\"}",
     "legendFormat": "Max Files"
    }
   ]
  },
  {
   "title": "Start time",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
   "format": "dateTimeAsIso",
   "valueName": "current",
   "targets": [
    {
     "expr": "process_start_time_seconds{pod=\"$pod\", pod=\"$pod\"}*1000"
    }
   ]
  },
  {
   "title": "Available CPUs",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_cpu_count{pod=\"$pod\"}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "system_cpu_usage{pod=\"$pod\", pod=\"$pod\"}",
     "legendFormat": "System CPU Usage"
    },
    {
     "expr": "process_cpu_usage{pod=\"$pod\", pod=\"$pod\"}",
     "legendFormat": "Process CPU Usage"
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "system_load_average_1m{pod=\"$pod\", pod=\"$pod\"}",
     "legendFormat": "Load Average [1m]"
    },
    {
     "expr": "system_cpu_count{pod=\"$pod\", pod=\"$pod\"}",
     "legendFormat": "CPU Core Size"
    }
   ]
  },
  { "title": "JVM Statistics - Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "$memory_pool_heap (heap)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 15 },
   "repeat": "memory_pool_heap",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{pod=\"$pod\", id=\"$memory_pool_heap\", pod=\"$pod\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "jvm_memory_committed_bytes{pod=\"$pod\", id=\"$memory_pool_heap\", pod=\"$pod\"}",
     "legendFormat": "Commited"
    },
    {
     "expr": "jvm_memory_max_bytes{pod=\"$pod\", d=\"$memory_pool_heap\", pod=\"$pod\"}",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "$memory_pool_heap (heap)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 15 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{pod=\"$pod\", id=\"$memory_pool_heap\", pod=\"$pod\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "jvm_memory_committed_bytes{pod=\"$pod\", id=\"$memory_pool_heap\", pod=\"$pod\"}",
     "legendFormat": "Commited"
    },
    {
     "expr": "jvm_memory_max_bytes{pod=\"$pod\", d=\"$memory_pool_heap\", pod=\"$pod\"}",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "$memory_pool_heap (heap)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 15 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{pod=\"$pod\", id=\"$memory_pool_heap\", pod=\"$pod\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "jvm_memory_committed_bytes{pod=\"$pod\", id=\"$memory_pool_heap\", pod=\"$pod\"}",
     "legendFormat": "Commited"
    },
    {
     "expr": "jvm_memory_max_bytes{pod=\"$pod\", d=\"$memory_pool_heap\", pod=\"$pod\"}",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "$memory_pool_nonheap (non-heap)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 23 },
   "repeat": "memory_pool_nonheap",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{pod=\"$pod\", id=\"$memory_pool_nonheap\", pod=\"$pod\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "jvm_memory_committed_bytes{pod=\"$pod\", id=\"$memory_pool_nonheap\", pod=\"$pod\"}",
     "legendFormat": "Commited"
    },
    {
     "expr": "jvm_memory_max_bytes{pod=\"$pod\", id=\"$memory_pool_nonheap\", pod=\"$pod\"}",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "$memory_pool_nonheap (non-heap)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 23 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{pod=\"$pod\", id=\"$memory_pool_nonheap\", pod=\"$pod\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "jvm_memory_committed_bytes{pod=\"$pod\", id=\"$memory_pool_nonheap\", pod=\"$pod\"}",
     "legendFormat": "Commited"
    },
    {
     "expr": "jvm_memory_max_bytes{pod=\"$pod\", id=\"$memory_pool_nonheap\", pod=\"$pod\"}",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "$memory_pool_nonheap (non-heap)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{pod=\"$pod\", id=\"$memory_pool_nonheap\", pod=\"$pod\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "jvm_memory_committed_bytes{pod=\"$pod\", id=\"$memory_pool_nonheap\", pod=\"$pod\"}",
     "legendFormat": "Commited"
    },
    {
     "expr": "jvm_memory_max_bytes{pod=\"$pod\", id=\"$memory_pool_nonheap\", pod=\"$pod\"}",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "$memory_pool_nonheap (non-heap)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 23 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{pod=\"$pod\", id=\"$memory_pool_nonheap\", pod=\"$pod\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "jvm_memory_committed_bytes{pod=\"$pod\", id=\"$memory_pool_nonheap\", pod=\"$pod\"}",
     "legendFormat": "Commited"
    },
    {
     "expr": "jvm_memory_max_bytes{pod=\"$pod\", id=\"$memory_pool_nonheap\", pod=\"$pod\"}",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "$memory_pool_nonheap (non-heap)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{pod=\"$pod\", id=\"$memory_pool_nonheap\", pod=\"$pod\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "jvm_memory_committed_bytes{pod=\"$pod\", id=\"$memory_pool_nonheap\", pod=\"$pod\"}",
     "legendFormat": "Commited"
    },
    {
     "expr": "jvm_memory_max_bytes{pod=\"$pod\", id=\"$memory_pool_nonheap\", pod=\"$pod\"}",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Classes Unloaded",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(jvm_classes_unloaded_classes_total{pod=\"$pod\", pod=\"$pod\"}[5m])",
     "legendFormat": "Classes Unloaded"
    }
   ]
  },
  {
   "title": "Classes Loaded",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "jvm_classes_loaded_classes{pod=\"$pod\"}",
     "legendFormat": "Classes Loaded"
    }
   ]
  },
  {
   "title": "Mapped Buffers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_buffer_memory_used_bytes{pod=\"$pod\", id=\"mapped\"}",
     "legendFormat": "Used Bytes"
    },
    {
     "expr": "jvm_buffer_total_capacity_bytes{pod=\"$pod\", id=\"mapped\"}",
     "legendFormat": "Capacity Bytes"
    }
   ]
  },
  {
   "title": "Memory Allocate/Promote",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "irate(jvm_gc_memory_allocated_bytes_total{pod=\"$pod\"}[5m])",
     "legendFormat": "allocated"
    },
    {
     "expr": "irate(jvm_gc_memory_promoted_bytes_total{pod=\"$pod\"}[5m])",
     "legendFormat": "promoted"
    }
   ]
  },
  {
   "title": "Direct Buffers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_buffer_memory_used_bytes{pod=\"$pod\", id=\"direct\"}",
     "legendFormat": "Used Bytes"
    },
    {
     "expr": "jvm_buffer_total_capacity_bytes{pod=\"$pod\", id=\"direct\"}",
     "legendFormat": "Capacity Bytes"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_daemon_threads{pod=\"$pod\"}",
     "legendFormat": "Daemon"
    },
    {
     "expr": "jvm_threads_live_threads{pod=\"$pod\"}",
     "legendFormat": "Live"
    },
    {
     "expr": "jvm_threads_peak_threads{pod=\"$pod\"}",
     "legendFormat": "Peak"
    }
   ]
  },
  { "title": "JVM Statistics - GC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 } },
  {
   "title": "GC Count",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "irate(jvm_gc_pause_seconds_count{pod=\"$pod\"}[5m])",
     "legendFormat": "{{action}} [{{cause}}]"
    }
   ]
  },
  {
   "title": "GC Stop the World Duration",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 63 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "irate(jvm_gc_pause_seconds_sum{pod=\"$pod\"}[5m])",
     "legendFormat": "{{action}} [{{cause}}]"
    }
   ]
  },
  { "title": "HikariCP Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 73 } },
  {
   "title": "Connections Size",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 74 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "hikaricp_connections{pod=\"$pod\", pool=\"HikariPool-1\"}"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 74 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hikaricp_connections_active{pod=\"$pod\", pool=\"HikariPool-1\"}",
     "legendFormat": "Active"
    },
    {
     "expr": "hikaricp_connections_idle{pod=\"$pod\", pool=\"HikariPool-1\"}",
     "legendFormat": "Idle"
    },
    {
     "expr": "hikaricp_connections_pending{pod=\"$pod\", pool=\"HikariPool-1\"}",
     "legendFormat": "Pending"
    }
   ]
  },
  {
   "title": "Connection Timeout Count",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 78 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "hikaricp_connections_timeout_total{pod=\"$pod\", pool=\"HikariPool-1\"}"
    }
   ]
  },
  {
   "title": "Connection Creation Time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 82 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "hikaricp_connections_creation_seconds_sum{pod=\"$pod\", pool=\"HikariPool-1\"} / hikaricp_connections_creation_seconds_count{pod=\"$pod\", pool=\"HikariPool-1\"}",
     "legendFormat": "Creation Time"
    }
   ]
  },
  {
   "title": "Connection Usage Time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 82 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "hikaricp_connections_usage_seconds_sum{pod=\"$pod\", pool=\"HikariPool-1\"} / hikaricp_connections_usage_seconds_count{pod=\"$pod\", pool=\"HikariPool-1\"}",
     "legendFormat": "Usage Time"
    }
   ]
  },
  {
   "title": "Connection Acquire Time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 82 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "hikaricp_connections_acquire_seconds_sum{pod=\"$pod\", pool=\"HikariPool-1\"} / hikaricp_connections_acquire_seconds_count{pod=\"$pod\", pool=\"HikariPool-1\"}",
     "legendFormat": "Acquire Time"
    }
   ]
  },
  { "title": "HTTP Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 88 } },
  {
   "title": "Request Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 89 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(http_server_requests_seconds_count{pod=\"$pod\", uri!~\".*actuator.*\"}[5m])",
     "legendFormat": "{{method}} [{{status}}] - {{uri}}"
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 96 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "irate(http_server_requests_seconds_sum{pod=\"$pod\", exception=\"None\", uri!~\".*actuator.*\"}[5m]) / irate(http_server_requests_seconds_count{pod=\"$pod\", exception=\"None\", uri!~\".*actuator.*\"}[5m])",
     "legendFormat": "{{method}} [{{status}}] - {{uri}}"
    }
   ]
  }
 ]
}