{
 "title": "Ceph & PostgreSQL Deep Scrubbing Dashboard",
 "tags": [
  "Ceph",
  "PostgreSQL"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Cluster",
    "query": {
     "query": "label_values(ceph_mon_quorum_status, job)"
    }
   },
   {
    "name": "mode",
    "query": {
     "query": "label_values(pg_locks_count, mode)"
    }
   },
   {
    "name": "pool_id",
    "query": {
     "query": "label_values(ceph_pg_scrubbing,pool_id)"
    }
   },
   {
    "name": "datname",
    "query": {
     "query": "label_values(pg_stat_activity_count, datname)"
    }
   },
   {
    "name": "osd_instances",
    "label": "Cluster",
    "query": {
     "query": "label_values(ceph_osd_metadata,hostname)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Ceph Deep Scrubbing Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Ceph Deep Scrubbing PGs",
   "type": "graph",
   "gridPos": { "h": 10, "w": 13, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(ceph_pg_deep) by (pool_id)", "legendFormat": "{{pool_id}}" }
   ]
  },
  {
   "title": "Cluster Healthy Status",
   "type": "alertlist",
   "gridPos": { "h": 10, "w": 10, "x": 13, "y": 1 },
   "targets": [
    {
     "expr": "ceph_health_status{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "OSD Read & Write Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "1000*sum(increase(ceph_osd_op_r_latency_sum{job=\"$job\"}[1m]))/clamp_min(sum(increase(ceph_osd_op_r_latency_count{job=\"$job\"}[1m])),1)",
     "legendFormat": "read"
    },
    {
     "expr": "1000*sum(increase(ceph_osd_op_w_latency_sum{job=\"$job\"}[1m]))/clamp_min(sum(increase(ceph_osd_op_w_latency_count{job=\"$job\"}[1m])),1)",
     "legendFormat": "write"
    },
    {
     "expr": "1000*sum(increase(ceph_osd_op_rw_latency_sum{job=\"$job\"}[1m]))/clamp_min(sum(increase(ceph_osd_op_rw_latency_count{job=\"$job\"}[1m])),1)",
     "legendFormat": "overwrite"
    }
   ]
  },
  {
   "title": "OSD Read & Write Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "1000*sum by (ceph_daemon) (increase(ceph_osd_op_r_latency_sum{job=\"$job\"}[1m]))/clamp_min(sum by (ceph_daemon) (increase(ceph_osd_op_r_latency_count{job=\"$job\"}[1m])),1)",
     "legendFormat": "{{ceph_daemon}} - read"
    },
    {
     "expr": "1000*sum by (ceph_daemon) (increase(ceph_osd_op_w_latency_sum{job=\"$job\"}[1m]))/clamp_min(sum by (ceph_daemon)(increase(ceph_osd_op_w_latency_count{job=\"$job\"}[1m])),1)",
     "legendFormat": "{{ceph_daemon}} - write"
    },
    {
     "expr": "1000*sum by (ceph_daemon) (increase(ceph_osd_op_rw_latency_sum{job=\"$job\"}[1m]))/clamp_min(sum by (ceph_daemon) (increase(ceph_osd_op_rw_latency_count{job=\"$job\"}[1m])),1)",
     "legendFormat": "{{ceph_daemon}} - overwrite"
    }
   ]
  },
  { "title": "Disk I/O Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Disk Read/Write Metrics",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total{instance=~\"$osd_instances\"}[5m])",
     "legendFormat": "reads {{device}}/{{instance}}"
    },
    {
     "expr": "rate(node_disk_written_bytes_total{instance=~\"$osd_instances\"}[5m])",
     "legendFormat": "writes {{device}}/{{instance}}"
    }
   ]
  },
  {
   "title": "Disk I/O Metrics",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_io_time_seconds_total{instance=~\"$osd_instances\"}[5m])",
     "legendFormat": "{{device}}/{{instance}}"
    }
   ]
  },
  {
   "title": " PostgreSQL Performance Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 }
  },
  {
   "title": "PostgreSQL Lock Waits",
   "type": "graph",
   "description": "If locks increase during deep scrubbing, Ceph I/O is likely affecting query performance.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum by (mode) (pg_locks_count)", "legendFormat": "{{mode}}" }
   ]
  },
  {
   "title": "PostgreSQL Active Queries",
   "type": "graph",
   "description": "Tracks the number of active queries.\nIf query counts drop during deep scrubs, it suggests an impact.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (datname) (pg_stat_activity_count{state=\"active\"})",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "PostgreSQL Blocks Read",
   "type": "graph",
   "description": "Shows read operations.\nIf reads increase significantly during scrubbing, it may indicate performance degradation.\nIf blks_read spikes significantly during degradation, it suggests PostgreSQL is evicting cached data more frequently and fetching from Ceph storage.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(pg_stat_database_blks_read[5m])",
     "legendFormat": "{{datname}}_read"
    }
   ]
  },
  {
   "title": "PostgreSQL Blocks Hit",
   "type": "graph",
   "description": "Shows cache efficiency.\nIf blks_hit drops suddenly, it means PostgreSQL is losing cached data, forcing expensive Ceph I/O operations.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(pg_stat_database_blks_hit[5m])",
     "legendFormat": "{{datname}}_hit"
    }
   ]
  }
 ]
}