{
 "title": "CEPH S3 Bucket Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Data Source", "query": "prometheus" },
   {
    "name": "bucket",
    "label": "Bucket",
    "query": {
     "query": "label_values(radosgw_usage_ops_total,bucket)"
    }
   },
   {
    "name": "interval",
    "label": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "job",
    "query": {
     "query": "label_values(ceph_mon_quorum_status,job)"
    }
   }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "PUT Operations per S3 Bucket (ops/s)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by (bucket) (rate(radosgw_usage_ops_total{category=\"put_obj\", bucket=~\"$bucket\"}[2m]))",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "GET Operations per S3 Bucket (ops/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (bucket) (rate(radosgw_usage_ops_total{category=\"get_obj\", bucket=~\"$bucket\"}[2m]))",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "Other S3 Bucket Ops",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "LIST Operations per S3 Bucket (ops/s)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "sum by (bucket) (rate(radosgw_usage_ops_total{category=\"list_buckets\", bucket=~\"$bucket\"}[2m]))",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "DELETE Operations per S3 Bucket (ops/s)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "sum by (bucket) (rate(radosgw_usage_ops_total{category=\"delete_obj\", bucket=~\"$bucket\"}[2m]))",
       "legendFormat": "{{bucket}}"
      }
     ]
    }
   ]
  },
  {
   "title": "S3 Bucket Volumes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "S3 Bucket Sizes",
     "type": "timeseries",
     "description": "Raw, unreplicated.",
     "gridPos": { "h": 7, "w": 19, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "dectbytes" } },
     "targets": [
      {
       "expr": "radosgw_usage_bucket_bytes{bucket=~\"$bucket\"}/1099511627776",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "S3 Storage Usage",
     "type": "gauge",
     "description": "Actual (raw - thats how much data is generated) and Replicated (thats how much storage is needed for it).",
     "gridPos": { "h": 7, "w": 5, "x": 19, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "dectbytes" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(radosgw_usage_bucket_bytes{bucket=~\"$bucket\"}/1099511627776)",
       "legendFormat": "Raw"
      },
      {
       "expr": "(sum(radosgw_usage_bucket_bytes{bucket=~\"$bucket\"}/1099511627776))*3",
       "legendFormat": "Replicated"
      }
     ]
    },
    {
     "title": "S3 Objects (Thousands)",
     "type": "timeseries",
     "description": "The number of objects within S3 buckets, multiply by 1000 to get exact value.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "radosgw_usage_bucket_objects{bucket=~\"$bucket\"}/1000",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "S3 Bucket Shards",
     "type": "timeseries",
     "description": "11 - default shards. We recomed for 100k objects per 1 shard for best S3 performance.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "radosgw_usage_bucket_shards{bucket=~\"$bucket\", bucket!=\"-\"}",
       "legendFormat": "{{ bucket }}"
      }
     ]
    },
    {
     "title": "Data Read Volume",
     "type": "timeseries",
     "description": "GET operations",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "GB/s" } },
     "targets": [
      {
       "expr": "sum by (bucket) (rate(radosgw_usage_received_bytes_total{bucket=~\"$bucket\"}[1m]) / 1073741824)",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "Data Write Volume",
     "type": "timeseries",
     "description": "PUT Operations",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "GB/s" } },
     "targets": [
      {
       "expr": "sum by (bucket) (rate(radosgw_usage_sent_bytes_total{bucket=~\"$bucket\"}[1m]) / 1073741824)\n",
       "legendFormat": "{{bucket}}"
      }
     ]
    }
   ]
  },
  {
   "title": "S3 Users",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "TOTAL Operations per S3 User (ops/s)",
     "type": "timeseries",
     "description": "Over the last 1min",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 4 },
     "targets": [
      {
       "expr": "sum(rate(radosgw_usage_user_total_objects[1m])) by (user)",
       "legendFormat": "{{user}}"
      }
     ]
    }
   ]
  },
  {
   "title": "S3 Activity Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "S3 Total Requests (ops/s)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "increase(ceph_rgw_req{job=\"$job\"}[1m])\n  * on(instance_id) group_left(ceph_daemon) label_join(ceph_rgw_metadata{job=\"$job\"}, \"ceph_daemon\", \"\", \"ceph_daemon\")\n",
       "legendFormat": "Rados Gateway: {{ceph_daemon}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Ceph Cluster Activity",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Ceph Scrubs",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "pgs" } },
     "targets": [
      { "expr": "sum(ceph_pg_scrubbing) by (pg)", "legendFormat": "Overall Cluster Scrubs" },
      {
       "expr": "sum(ceph_pg_scrubbing * on(pool_id) group_left(name) ceph_pool_metadata{name=~\".*rgw.buckets.data*\"}) by (pg)",
       "legendFormat": "S3 Data Shallow Scrubs"
      },
      {
       "expr": "sum(ceph_pg_deep * on(pool_id) group_left(name) ceph_pool_metadata{name=~\".*rgw.buckets.data*\"}) by (pg)",
       "legendFormat": "S3 Data Deep Scrubs"
      },
      {
       "expr": "(sum(ceph_pg_scrubbing * on(pool_id) group_left(name) ceph_pool_metadata{name=~\".*rgw.meta*\"}) by (pg))+(sum(ceph_pg_deep * on(pool_id) group_left(name) ceph_pool_metadata{name=~\".*rgw.meta*\"}) by (pg))",
       "legendFormat": "RadosGW Metadata Scrubs"
      },
      {
       "expr": "(sum(ceph_pg_scrubbing * on(pool_id) group_left(name) ceph_pool_metadata{name=~\".*rgw.buckets.index*\"}) by (pg))+(sum(ceph_pg_deep * on(pool_id) group_left(name) ceph_pool_metadata{name=~\".*rgw.buckets.index*\"}) by (pg))",
       "legendFormat": "S3 Index Scrubs"
      },
      {
       "expr": "((sum(ceph_pg_backfilling * on(pool_id) group_left(name) ceph_pool_metadata{name=~\".*rgw.buckets.non-ec*\"}) by (pg)))+((sum(ceph_pg_backfilling * on(pool_id) group_left(name) ceph_pool_metadata{name=~\".*rgw.control*\"}) by (pg)))+((sum(ceph_pg_backfilling * on(pool_id) group_left(name) ceph_pool_metadata{name=~\".*rgw.log*\"}) by (pg)))+((sum(ceph_pg_backfilling * on(pool_id) group_left(name) ceph_pool_metadata{name=~\".*rgw.root*\"}) by (pg)))",
       "legendFormat": "Other Pool Scrubs"
      }
     ]
    },
    {
     "title": "Ceph Backfills",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "pgs" } },
     "targets": [
      {
       "expr": "sum(ceph_pg_backfilling) by (pg)",
       "legendFormat": "All Placement Groups"
      },
      {
       "expr": "(sum(ceph_pg_backfilling * on(pool_id) group_left(name) ceph_pool_metadata{name=~\".*rgw.buckets.data*\"}) by (pg))+((sum(ceph_pg_backfilling * on(pool_id) group_left(name) ceph_pool_metadata{name=~\".*rgw.buckets.index*\"}) by (pg)))+((sum(ceph_pg_backfilling * on(pool_id) group_left(name) ceph_pool_metadata{name=~\".*rgw.buckets.non-ec*\"}) by (pg)))",
       "legendFormat": "S3 Bucket Placement Groups"
      },
      {
       "expr": "(sum(ceph_pg_backfilling * on(pool_id) group_left(name) ceph_pool_metadata{name=~\".*rgw.meta*\"}))+((sum(ceph_pg_backfilling * on(pool_id) group_left(name) ceph_pool_metadata{name=~\".*rgw.control*\"}) by (pg)))+((sum(ceph_pg_backfilling * on(pool_id) group_left(name) ceph_pool_metadata{name=~\".*rgw.log*\"}) by (pg)))+((sum(ceph_pg_backfilling * on(pool_id) group_left(name) ceph_pool_metadata{name=~\".*rgw.root*\"}) by (pg)))",
       "legendFormat": "RadosGW Placement Groups"
      }
     ]
    },
    {
     "title": "Ceph S3 Active Placement Groups (Pools)",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 22 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "sum(ceph_pg_active) by (pg)", "legendFormat": "Cluster Total PGs" },
      {
       "expr": "sum(ceph_pg_active * on(pool_id) group_left(name) ceph_pool_metadata{name=~\".*rgw.buckets.data*\"}) by (pg)",
       "legendFormat": "S3 Data PGs"
      },
      {
       "expr": "sum(ceph_pg_active * on(pool_id) group_left(name) ceph_pool_metadata{name=~\".*rgw.meta*\"}) by (pg)",
       "legendFormat": "Metadata PGs"
      },
      {
       "expr": "sum(ceph_pg_active * on(pool_id) group_left(name) ceph_pool_metadata{name=~\".*rgw.buckets.index*\"}) by (pg)",
       "legendFormat": "Index PGs"
      },
      {
       "expr": "sum(ceph_pg_active * on(pool_id) group_left(name) ceph_pool_metadata{name=~\".*rgw.log*\"}) by (pg)",
       "legendFormat": "Log PGs"
      },
      {
       "expr": "sum(ceph_pg_active * on(pool_id) group_left(name) ceph_pool_metadata{name=~\".*rgw.buckets.non-ec*\"}) by (pg)",
       "legendFormat": "Non-EC PGs"
      },
      {
       "expr": "sum(ceph_pg_active * on(pool_id) group_left(name) ceph_pool_metadata{name=~\".*rgw.control*\"}) by (pg)",
       "legendFormat": "Control PGs"
      },
      {
       "expr": "sum(ceph_pg_active * on(pool_id) group_left(name) ceph_pool_metadata{name=~\".*rgw.root*\"}) by (pg)",
       "legendFormat": "Root PGs"
      }
     ]
    }
   ]
  },
  {
   "title": "Ceph Disk Latencies",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "OSD Overall Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "1000*sum(increase(ceph_osd_op_r_latency_sum{job=\"$job\"}[1m]))/clamp_min(sum(increase(ceph_osd_op_r_latency_count{job=\"$job\"}[1m])),1)",
       "legendFormat": "read"
      },
      {
       "expr": "1000*sum(increase(ceph_osd_op_w_latency_sum{job=\"$job\"}[1m]))/clamp_min(sum(increase(ceph_osd_op_w_latency_count{job=\"$job\"}[1m])),1)",
       "legendFormat": "write"
      },
      {
       "expr": "1000*sum(increase(ceph_osd_op_rw_latency_sum{job=\"$job\"}[1m]))/clamp_min(sum(increase(ceph_osd_op_rw_latency_count{job=\"$job\"}[1m])),1)",
       "legendFormat": "overwrite"
      }
     ]
    },
    {
     "title": "Commit Latency - per OSD",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "ceph_osd_commit_latency_ms{job=\"$job\"}",
       "legendFormat": "{{ceph_daemon}}"
      }
     ]
    },
    {
     "title": "Apply Latency - per OSD",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "ceph_osd_apply_latency_ms{job=\"$job\"}",
       "legendFormat": "{{ceph_daemon}}"
      }
     ]
    },
    {
     "title": "Read Latency - sum per 1 min",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "rate(ceph_osd_op_r_latency_sum{job=\"$job\"}[1m])",
       "legendFormat": "{{ceph_daemon}}"
      }
     ]
    },
    {
     "title": "Total Ops History per OSD",
     "type": "timeseries",
     "description": "A counter to see which disks have been used the most",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 45 },
     "targets": [
      {
       "expr": "ceph_osd_op{job=\"$job\"}",
       "legendFormat": "Disk: {{ceph_daemon}}"
      }
     ]
    }
   ]
  }
 ]
}