{
 "title": "Registry Configuration Audit",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "ns",
    "label": "Registry",
    "query": {
     "query": "label_values(kube_deployment_spec_replicas{deployment=\"bpms\"}, namespace)"
    }
   },
   {
    "name": "node_names",
    "query": {
     "query": "label_values(kube_pod_info{namespace=\"$ns\"}, node)"
    }
   }
  ]
 },
 "panels": [
  { "title": "1. Container resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Container memory",
   "type": "table",
   "gridPos": { "h": 13, "w": 10, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "label_join(\n  sum(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"$ns\", container!=\"\", image!=\"\"}) by (pod, container),\n  \"pod_container\", \"-\", \"pod\", \"container\"\n)"
    },
    {
     "expr": "label_join(\n  sum by (pod, container) (kube_pod_container_resource_requests{namespace=\"$ns\", resource=\"memory\"}),\n  \"pod_container\", \"-\", \"pod\", \"container\"\n)"
    },
    {
     "expr": "label_join(\n  sum by (pod, container) (kube_pod_container_resource_limits{namespace=\"$ns\", resource=\"memory\"}),\n  \"pod_container\", \"-\", \"pod\", \"container\"\n)"
    }
   ]
  },
  {
   "title": "Replicas count",
   "type": "table",
   "gridPos": { "h": 13, "w": 7, "x": 10, "y": 1 },
   "targets": [
    {
     "expr": "label_replace(\n  sum by (deployment) (kube_deployment_spec_replicas{namespace=\"$ns\"}),\n  \"resource_type\", \"Deployment\", \"\", \"\"\n)\nor\nlabel_replace(\n  sum by (statefulset) (kube_statefulset_replicas{namespace=\"$ns\"}),\n  \"resource_type\", \"StatefulSet\", \"\", \"\"\n)"
    }
   ]
  },
  { "title": "2. Nodes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Nodes Capacity",
   "type": "table",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "sum by (node) (machine_cpu_cores{node=~\"$node_names\"})"
    },
    {
     "expr": "label_replace((sum by (instance) (node_memory_MemTotal_bytes{instance=~\"$node_names\"})), \"node\", \"$1\", \"instance\", \"(.*)\")"
    }
   ]
  },
  {
   "title": "Node Taints",
   "type": "table",
   "gridPos": { "h": 8, "w": 10, "x": 7, "y": 15 },
   "targets": [
    {
     "expr": "sum by (node, key, value, effect) (kube_node_spec_taint{node=~\"$node_names\"})"
    }
   ]
  },
  {
   "title": "3. Java",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Java Opts Resources",
     "type": "table",
     "gridPos": { "h": 14, "w": 15, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(jvm_memory_committed_bytes{namespace=\"$ns\", area=\"heap\"}) by (pod, service)"
      },
      {
       "expr": "sum(jvm_memory_max_bytes{namespace=\"$ns\", area=\"heap\"}) by (pod, service)"
      },
      {
       "expr": "sum(jvm_memory_bytes_max{area=\"heap\",namespace=\"$ns\",job!=\"kafka-cluster-zookeeper-client\",job!=\"kafka-cluster-zookeeper-nodes\", job!=\"kafka-cluster-kafka-brokers\",job!=\"kafka-cluster-kafka-bootstrap\"}) by (pod)"
      },
      {
       "expr": "sum(jvm_memory_bytes_init{area=\"heap\",namespace=\"$ns\",job!=\"kafka-cluster-zookeeper-client\",job!=\"kafka-cluster-zookeeper-nodes\", job!=\"kafka-cluster-kafka-brokers\",job!=\"kafka-cluster-kafka-bootstrap\"}) by (pod)"
      },
      {
       "expr": "sum(system_cpu_count{namespace=\"$ns\", service !=\"platform-gateway-public-api\", service !=\"platform-gateway-public-documentation\"}) by (pod)"
      },
      {
       "expr": "sum by (pod) (kube_pod_container_resource_requests{namespace=\"$ns\", resource=\"memory\", container!=\"istio-proxy\"})"
      },
      {
       "expr": "sum by (pod) (kube_pod_container_resource_limits{namespace=\"$ns\", resource=\"memory\", container!=\"istio-proxy\"})"
      }
     ]
    }
   ]
  },
  { "title": "4. Database", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Storage Size",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_persistentvolumeclaim_resource_requests_storage_bytes{namespace=\"$ns\", persistentvolumeclaim=~\"operational-instance1-.*\"}"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 5, "x": 4, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (cluster) (pg_settings_max_connections{namespace=\"$ns\", cluster=\"operational\"})"
    },
    {
     "expr": "sum (hikaricp_connections_max{namespace=\"$ns\"})"
    }
   ]
  },
  {
   "title": "Essential Database Config",
   "type": "table",
   "gridPos": { "h": 3, "w": 15, "x": 9, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (\n  kube_pod_container_resource_requests{namespace=\"$ns\", resource=\"memory\", pod=~\"operational-instance.*\"}\n) OR absent(kube_pod_container_resource_requests{namespace=\"$ns\", resource=\"memory\", pod=~\"operational-instance.*\"})\n"
    },
    {
     "expr": "sum by (pod) (\n  kube_pod_container_resource_limits{namespace=\"$ns\", resource=\"memory\", pod=~\"operational-instance.*\"}\n) OR absent(kube_pod_container_resource_limits{namespace=\"$ns\", resource=\"memory\", pod=~\"operational-instance.*\"})"
    },
    {
     "expr": "sum by (pod) (pg_settings_shared_buffers_bytes{cluster=\"operational\", namespace=\"$ns\"})"
    },
    {
     "expr": "sum by (pod) (pg_settings_effective_cache_size_bytes{cluster=\"operational\", namespace=\"$ns\"})"
    },
    {
     "expr": "sum by (pod) (pg_settings_max_wal_size_bytes{cluster=\"operational\", namespace=\"$ns\"})"
    }
   ]
  },
  {
   "title": "Operational Instance Pod Tolerations",
   "type": "table",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 28 },
   "targets": [
    {
     "expr": "sum by (key, operator) (kube_pod_tolerations{namespace=\"$ns\", pod=~\"operational-instance.*\", key!~\"node.kubernetes.io/.*\"})"
    }
   ]
  },
  {
   "title": "Connection pools by clients",
   "type": "table",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "sum by (pod) (hikaricp_connections_max{namespace=\"$ns\"})"
    }
   ]
  },
  { "title": "5. Istio", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Istio Container Resorces",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (kube_pod_container_resource_requests{namespace=\"$ns\", container=\"istio-proxy\", resource=\"memory\"})"
    },
    {
     "expr": "sum by (pod) (kube_pod_container_resource_requests{namespace=\"$ns\", container=\"istio-proxy\", resource=\"cpu\"})"
    },
    {
     "expr": "sum by (pod) (kube_pod_container_resource_limits{namespace=\"$ns\", container=\"istio-proxy\", resource=\"memory\"})"
    },
    {
     "expr": "sum by (pod) (kube_pod_container_resource_limits{namespace=\"$ns\", container=\"istio-proxy\", resource=\"cpu\"})"
    }
   ]
  },
  { "title": "6. Kafka", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "Brokers Online",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 47 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kafka_server_replicamanager_leadercount{namespace=\"$ns\", service=\"kafka-cluster-kafka-brokers\"})"
    }
   ]
  },
  {
   "title": "BPM History Events Topics",
   "type": "table",
   "gridPos": { "h": 5, "w": 7, "x": 5, "y": 47 },
   "targets": [
    {
     "expr": "sum by (topic) (kafka_topic_partitions{namespace=\"$ns\", topic=~\"bpm-history.*\"})"
    }
   ]
  },
  {
   "title": "Process History Service Persistence Replicas",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 12, "y": 47 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (deployment) (kube_deployment_spec_replicas{namespace=\"$ns\", deployment=\"process-history-service-persistence-deployment\"})"
    }
   ]
  }
 ]
}